title: Your Website's Title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal website hosted on GitHub Pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site
twitter_username: yourusername
github_username:  yourusername

theme: minima # or any other theme you choose
