title: "Bach PHAN-TAT"
author: "Bach PHAN-TAT"
description: "Bach's personal site"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "README.md", title: "Home", icon: user}
  - {file: "cv.md", title: "CV", icon: "fa-solid fa-file-lines"}
  - {file: "articles.md", title: "Articles", icon: "fa-solid fa-book-open"}
  - {file: "classes.md", title: "Classes", icon: "fa-solid fa-chalkboard-teacher"}


external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:phantatbach@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/phantatbach"}
  - {title: Facebook, icon: facebook, url: "https://facebook.com/phantatbach"}
  - {title: twitter, icon: twitter, url: "https://x.com/phantatbach"}
  # - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
