title: Phan Tất Bách
email: phantatbach@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My personal site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://phantatbach.github.io" # the base hostname & protocol for your site
twitter_username: phantatbach
github_username: phantatbach
facebook_username: phantatbach
linkedin_username: phantatbach
youtube_username: @bachphantat

theme: minima # or any other theme you choose
exclude:
  - README.md

